# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Francois Role's Pages
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://franrole.github.io" # the base hostname & protocol for your site
twitter_username: na
github_username:  franrole

# Build settings
markdown: kramdown


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "francois.role@u-paris.fr"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 
      author: "francois.role@u-paris.fr"


# Liste des catégories https://www.valhalla.fr/2017/10/16/jekyll-une-page-par-categorie/
collections:
  category:
    output: true # générer la page HTML
    permalink: /:collection/:name/index.html
    # exemple -> /category/ML/index.html

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
      # layout utilisé -> _layouts/category.html

