# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Francois Role's Pages
email: francois.role@u-paris.fr
description: > # this means to ignore newlines until "baseurl:"
  This site is about ML techniques with an emphasis on usupervised NLP and text mining techniques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://franrole.github.io" # the base hostname & protocol for your site
# twitter_username: na
github_username:  franrole

# Build settings
markdown: kramdown


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "francois.role@u-paris.fr"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 
      author: "francois.role@u-paris.fr"


# Liste des catégories https://www.valhalla.fr/2017/10/16/jekyll-une-page-par-categorie/
collections:
  category:
    output: true # générer la page HTML
    permalink: /:collection/:name/index.html
    # exemple -> https://franrole.github.io/category/ml/index.html
    # file is ML.md !!!

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
      # layout utilisé -> _layouts/category.html

header_pages:
  - about.md
  - browse.md

# show_excerpts: true

author:
  name: Francois Role
  email: "francois.role@u-paris.fr"

theme: jekyll-theme-minimal

minima:
  skin: dark

# $orange-color

# https://www.valhalla.fr/2017/10/16/jekyll-une-page-par-categorie/

